- hosts: localhost
  name: Run Tests
  vars:
    delete_demo: false
    verify_tls: false
    insecure_skip_tls_verify: true
    num_users: 20
    run_pipelines: false
    run_benchmarks: true
    ultimate_benchmark_cpu: false
    ultimate_benchmark_memory: true
    benchmark: benchmark.json.j2
    serverless_app_memory_limit: 1.5Gi
    serverless_app_cpu_limit: 2
    serverless_app_memory_request: 250Mi
    serverless_app_cpu_request: 200m
  tasks:
    - name: Get openshift console
      kubernetes.core.k8s_info:
        validate_certs: '{{ verify_tls }}'
        kind: Route
        name: console
        namespace: openshift-console
        api_version: route.openshift.io/v1
      register: openshift_console_route

    - name: Set openshift console
      ansible.builtin.set_fact:
        console_url: "https://{{ openshift_console_route.resources[0].status.ingress[0].host }}"

    - name: Define domain
      ansible.builtin.set_fact:
        domain: "{{ console_url | regex_replace('https://console-openshift-console.apps.') }}"

    - name: Set Subdomain
      ansible.builtin.set_fact:
        route_subdomain: "apps.{{ domain }}"

    - name: Create Usernames
      ansible.builtin.set_fact:
        users: "{{ users | default([]) + ['user' + item | string] }}"
      loop: "{{ range(1, ((num_users | int) + 1)) | list }}"

    - name: Run pipelines
      ansible.builtin.include_tasks: run_pipelines.yml
      loop: '{{ users }}'
      when: run_pipelines | bool

    - name: Evaluate Deployments
      kubernetes.core.k8s:
        validate_certs: '{{ verify_tls }}'
        state: present
        api_version: serving.knative.dev/v1
        kind: Service
        definition:
          metadata:
            name: quarkus-app
            namespace: '{{ item }}-staging'
      loop: '{{ users }}'
      register: _services
      retries: 50
      delay: 30
      when: run_benchmarks | bool
      until:
        - _services is succeeded

    - name: Update Knative
      ansible.builtin.include_tasks: update_serverless.yml
      loop: '{{ users }}'
      when: run_benchmarks | bool

    - name: Run Benchmarks
      ansible.builtin.include_tasks: run_benchmarks.yml
      loop: '{{ users }}'
      when: run_benchmarks | bool
